### Creer une vente
POST http://localhost:8080/api/ventes
Content-Type: application/json

{
    "clientId": 1,
    "utilisateurId": 1,
    "lignes": [
        {
            "produitId": 1,
            "quantite": 2
        }
    ]
}